### ISSUE TITLE
CheckoutInformationPage.cshtml line 99 PaymentInfo should be ShippingInfo

### ISSUE THREAD

**Issue by palcon-dc** [umbraco/Umbraco.Commerce.DemoStore#11]
`<!option value="@(country.Id)" @Html.Raw(Model.Order.PaymentInfo.CountryId == country.Id ? "selected=\"selected\"" : "")>@(country.Name)</!option>`

Should be

`<!option value="@(country.Id)" @Html.Raw(Model.Order.ShippingInfo.CountryId == country.Id ? "selected=\"selected\"" : "")>@(country.Name)</!option>`

**Comment by mattbrailsford** [comment]
PR #12 with bug fix merged in.

Thanks for reporting and submitting the PR

**Comment by palcon-dc** [comment]
You're welcome, and thank you for this great resource.
