### ISSUE TITLE
Creating Sub Document Type like DemoStore Page and CartPage 

### ISSUE THREAD

**Issue by ferhat-aksoy** [umbraco/Umbraco.Commerce.DemoStore#13]
Hi Matt,

I have a problem with creating a Document Type in the backoffice settings. I cloned your demo store project, and when I create a new page and inherit from the Page Document Type, my new page doesn't show up under the Page Elements in the Settings menu, like the CartPage or Search Page do. Could you help me fix this? If you have any resources to learn from, I'd appreciate it. I checked the Umbraco documents, but they seem to be for older versions. @mattbrailsford 

![image](https://github.com/user-attachments/assets/23a126d5-8d2f-4c3c-8a96-411d031a9006)
![image](https://github.com/user-attachments/assets/a08dc3f4-cece-4928-83da-29201ea3e329)

**Comment by mattbrailsford** [comment]
Sorry I'm not quite understanding, when you say "my new page doesn't show up under the Page Elements in the Settings menu" which menu do you mean? Can you provide a screenshot?

**Comment by ferhat-aksoy** [comment]
![1](https://github.com/user-attachments/assets/0c9eae06-fbec-441a-a98c-21a1bc26b65d)
![2](https://github.com/user-attachments/assets/205d9bd3-5c2e-4baa-93ac-4b1dd052d980)
@mattbrailsford i want to move FarhadPage under Page DocumnetType like CartPage in ScreenShot
f.hemmatzadeh@gmail.com

**Comment by mattbrailsford** [comment]
Ahh, this would then be a CMS issue not an Umbraco Commerce issue. I don't think you can move doc types, rather you should be able to create a child document type to the "Page" doc type from the three dots menu but I think that isn't currently working. I have a similar issue raised here https://github.com/umbraco/Umbraco-CMS/issues/16872 but I don't think yours is entirely the same so you may need to raise a new one.
