### ISSUE TITLE
branch support/13.x throws no macro found by alias exception when trying to access the store front

### ISSUE THREAD

**Issue by umbracotrd** [umbraco/Umbraco.Commerce.DemoStore#16]
At [this commit](https://github.com/umbraco/Umbraco.Commerce.DemoStore/tree/81f4ea0dc816f329ce5b6c770ea5567287018fcb) of branch `support/13.x`, when I go to the store front's home page, the server throws `No macro found by alias...` exception.

I had to comment out [this line](https://github.com/umbraco/Umbraco.Commerce.DemoStore/blob/81f4ea0dc816f329ce5b6c770ea5567287018fcb/src/Umbraco.Commerce.DemoStore.Web/Views/Page.cshtml#L31) as a workaround to continue with my development locally.

**Comment by mattbrailsford** [comment]
What database are you using?

**Comment by umbracotrd** [comment]
I use sql server restored from the `UmbracoCommerceDemoStore_v13.1.0.bacpac` in the repo

**Comment by mattbrailsford** [comment]
Ok, let me check that got updated

**Comment by mattbrailsford** [comment]
Bacpac file has now been updated with missing changes 👍
