### ISSUE TITLE
Trying to run demo store using the DemoStore_v13_starter.bacpac results in Error during installation

### ISSUE THREAD

**Issue by davidclintontitanwebtech** [umbraco/Umbraco.Commerce.DemoStore#7]
I've pulled down a copy of the demo store and set it up to run against a database created by importing the DemoStore_v13_starter.bacpac. When running the solution and logging in to the back office the "Detected current version (c76d9c9a), which needs to be upgraded to 13.0.0 (6158f3a3)." message is displayed but when I click continue the following error is displayed:

_Error during installation
The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid column name 'exceptionOccured'. Please check log file for additional information (can be found in 'LoggingSettings.Directory')

See the log for full details (logs can typically be found in the umbraco\Logs folder)._

Here is the error from the log:

{"@t":"2024-02-07T15:50:21.6835375Z","@mt":"An error occurred during installation step {Step}","@l":"Error","@x":"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.\r\n ---> Umbraco.Cms.Core.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid column name 'exceptionOccured'.\n Please check log file for additional information (can be found in 'LoggingSettings.Directory')\r\n   at Umbraco.Cms.Infrastructure.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model)\r\n   at InvokeStub_InstallSetupStep`1.ExecuteAsync(Object, Span`1)\r\n   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   --- End of inner exception stack trace ---\r\n   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\r\n   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.ExecuteStepAsync(InstallSetupStep step, Object instruction)\r\n   at Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall(InstallInstructions installModel)","@tr":"50ba4d8c5ddafacae56e8d1d6688badc","@sp":"1e995a57966ec164","Step":"DatabaseUpgrade","SourceContext":"Umbraco.Cms.Web.BackOffice.Install.InstallApiController","ActionId":"32feb255-49bf-4ae2-a076-49cfa4c23fc0","ActionName":"Umbraco.Cms.Web.BackOffice.Install.InstallApiController.PostPerformInstall (Umbraco.Web.BackOffice)","RequestId":"8000005b-000a-f900-b63f-84710c7967bb","RequestPath":"/install/api/PostPerformInstall","ProcessId":45240,"ProcessName":"iisexpress","ThreadId":5,"ApplicationId":"26d01aefaa39ffd521f099d63e43d3b447478d8d"}

Our dev server is running the latest version of SQL Server 2022 and I believe the latest version of SQL Server Management Studio (19.3) was used when doing the import.

Also just to note I've also just tried this using the default SQLite set up and the upgrade seemed to work perfectly.

**Comment by mattbrailsford** [comment]
Hmm, sounds like the database could be a little out of sync and maybe it thinks some migrations have run that haven't (specifically this one https://github.com/umbraco/Umbraco-CMS/blob/7046c3585b65b0fb3e6d87ad640035f2be7f3b66/src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs#L107)

You might need to update the umbraco key value database table to make it think it's running on an older version of Umbraco to force it to re-run the v13 migrations (so maybe use the value `2D4C9FBD-08B3-472D-A76C-6ED467A0CD20`)

Hopefully that should force the creation of that missing column.

**Comment by HensorIn** [comment]
I had the same issue, but upgrading the Umbraco version through nuget to 13.2.2 worked for me.

**Comment by davidclintontitanwebtech** [comment]
Ah yes I should have said we upgraded to a later version and it worked fine so I'll mark this closed.
